name: 03-devops-basico-CI

on:
  push:
    branches: [main]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4.2.2

       - name: Run a one line command
         run: echo hello world!


